POST http://localhost:8080/api/v1/playlist/video/public/create
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTc0NjU4ODQsImV4cCI6MTY1NzQ2OTQ4NCwiaXNzIjoiWW91dHViZSBwcm9qZWN0IiwiaWQiOjF9.HQ7vIJV8AKMa0w1nF25esvWDimZgQKRCw1tmn9v2zpA
Content-Type: application/json

{
  "videoId": "402880ec81e89f590181e89fe9cc0001",
  "playlistId": "402880ec81e8a9f60181e8aeb4570000",
  "order": 1,
  "channelId": ""
}